# Generated by Django 4.2.1 on 2023-06-05 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeequipment',
            name='recipe',
        ),
        migrations.AddField(
            model_name='dish',
            name='equip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.recipeequipment'),
        ),
    ]
