# Generated by Django 4.2.1 on 2023-06-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_recipeequipment_recipe_dish_equip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipeequipment'),
        ),
    ]
